export const Damage = {
  Acid: "Acid",
  Bludgeoning: "Bludgeoning",
  Cold: "Cold",
  Fire: "Fire",
  Force: "Force",
  Lightning: "Lightning",
  Necrotic: "Necrotic",
  Piercing: "Piercing",
  Poison: "Poison",
  Psychic: "Psychic",
  Radiant: "Radiant",
  Slashing: "Slashing",
  Thunder: "Thunder",
} as const;
